//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int MensajeId { get; set; }
        public string Contenido { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public int EmisorId { get; set; }
        public int ReceptorId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
