//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokemonGameDBEntities : DbContext
    {
        public PokemonGameDBEntities()
            : base("name=PokemonGameDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntrenadoresPokemone> EntrenadoresPokemones { get; set; }
        public virtual DbSet<Mensaje> Mensajes { get; set; }
        public virtual DbSet<Pokedex> Pokedexes { get; set; }
        public virtual DbSet<Pokemone> Pokemones { get; set; }
        public virtual DbSet<SolicitudesAtencion> SolicitudesAtencions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
