//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemone()
        {
            this.EntrenadoresPokemones = new HashSet<EntrenadoresPokemone>();
            this.SolicitudesAtencions = new HashSet<SolicitudesAtencion>();
        }
    
        public int PokemonId { get; set; }
        public string Nombre { get; set; }
        public byte[] Foto { get; set; }
        public string Tipo { get; set; }
        public string Debilidad { get; set; }
        public string Evoluciones { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public int Numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrenadoresPokemone> EntrenadoresPokemones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesAtencion> SolicitudesAtencions { get; set; }
    }
}
